# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import no_thanks_pb2 as no__thanks__pb2


class NoThanksStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_unary(
        '/no_thanks.NoThanks/Register',
        request_serializer=no__thanks__pb2.RegisterRequest.SerializeToString,
        response_deserializer=no__thanks__pb2.RegisterResponse.FromString,
        )


class NoThanksServicer(object):

  def Register(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NoThanksServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_unary_rpc_method_handler(
          servicer.Register,
          request_deserializer=no__thanks__pb2.RegisterRequest.FromString,
          response_serializer=no__thanks__pb2.RegisterResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'no_thanks.NoThanks', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
